config/routes.rb
Kevlinks::Application.routes.draw do

  devise_for :users
  get "welcome/index"
  get "welcome/about"
  get "welcome/example"

  root to: 'welcome#index'
  
  resources :posts do
    get '/move_up', to: 'posts#move_up'
    get '/move_down', to: 'posts#move_down'
    get '/move_folder', to: 'posts#move_folder'
    get '/paste_into_folder', to: 'posts#paste_into_folder'
    get '/paste_cancel', to: 'posts#paste_cancel'
  end
  resources :users, only: [:index, :show]

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_ancestry(orphan_strategy: :destroy)
  belongs_to :user

  after_create :move_to_bottom

  validates :title, length: {minimum: 1}, if: "ptype == FOLDER_TYPE"

  def getTypeString
    case self.ptype
    when FOLDER_TYPE
      "folder"
    when BLOG_TYPE
      "blog"
    when TWEET_TYPE
      "note"
    when LINK_TYPE
      "link"
    end
  end

  def move_higher
    puts "Entered move_higher for '"+ self.title + "' (id: "+ self.id.to_s + ")"
    if self.is_root? || self.is_only_child?
      puts "Is only child."
      self.update(position: 0)
      return
    end

    my_position = self.position
    puts "My_position: " + my_position.to_s
    my_siblings = self.siblings.order(:position)

    my_siblings.each do |s|
      puts s.position.to_s
    end

    # For now, assume each position value is unique within siblings
    sibling_above = my_siblings.first
    puts "My first sibling's position: " + sibling_above.position.to_s
    my_siblings.each do |s|
      puts "s.id: " + s.id.to_s
      puts "s.title: " + s.title
      if s.id == self.id
        new_position = sibling_above.position

        sibling_above.update(position: my_position)
        self.update(position: new_position)
        return
      end
      sibling_above = s
    end

  end

  def move_lower
    puts "Entered move_lower"
    if self.is_root? || self.is_only_child?
      self.update(position: 0)
      return
    end

    my_siblings = self.siblings.order(:position).reverse_order
    sibling_below = my_siblings.first
    my_siblings.each do |s|
      if s.id == self.id
        new_position = sibling_below.position

        sibling_below.update(position: self.position)
        self.update(position: new_position)

        return
      end
      sibling_below = s
    end
  end

  def move_to_top
    puts "Entered move_to_top() for " + self.title

    if self.is_root? || self.is_only_child?
      puts "move_to_top only child."
      self.update(position: 0)
      return
    end

    puts self.title + " supposedly has siblings (next line):"

    my_siblings = self.siblings.order(:position)

    lowest_position = my_siblings.minimum("position")
    puts "Lowest position: " + lowest_position.to_s
    self.update(position: (lowest_position - 1))
    puts "Exited move_top_top."
  end

  def move_to_bottom
    if self.is_root? || self.is_only_child?
      self.position = 0
      self.save
      return
    end

    my_siblings = self.siblings.order(:position).reverse_order
    highest_position = my_siblings.maximum("position")
    self.update(position: (highest_position + 1))

  end

  def icon
    case self.ptype
    when FOLDER_TYPE
      "glyphicon glyphicon-folder-open"
    when BLOG_TYPE
      "glyphicon glyphicon-comment"
    when LINK_TYPE
      "glyphicon glyphicon-bookmark"
    when TWEET_TYPE
      "glyphicon glyphicon-pushpin"
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def move_folder
    @post = Post.find(params[:post_id])
    if !current_user || (current_user != @post.user)
      redirect_to @post.parent
      return
    end

    # Store post id into cookie's :cut value
    session[:cutPostValue] = @post.id
    redirect_to @post.parent
  end

  def paste_into_folder
    @post = Post.find(params[:post_id])
    if !current_user || (current_user != @post.user)
      redirect_to @post.parent
      return
    end

    # If there is a value > 0 in the cookie's :cut value
    # Find the post with that value ID and update it's parent to be this folder
    # Then clear the cookie's value
    if (session[:cutPostValue] && session[:cutPostValue] > 0)

      postToMove = Post.find(session[:cutPostValue])
      postToMove.parent = @post
      postToMove.save
      postToMove.move_to_top

    end
    session[:cutPostValue] = 0
    redirect_to @post
  end

  def paste_cancel
    @post = Post.find(params[:post_id])
    if !current_user || (current_user != @post.user)
      redirect_to @post.parent
      return
    end

    # Clear the cookie's :cut value
    session[:cutPostValue] = 0
    redirect_to @post
  end

  def move_down
    @post = Post.find(params[:post_id])
    if !current_user || (current_user != @post.user)
      redirect_to @post.parent
      return
    end

    @post.move_lower
    redirect_to @post.parent
  end

  def move_up
    @post = Post.find(params[:post_id])
    if !current_user || (current_user != @post.user)
      redirect_to @post.parent
      return
    end

    @post.move_higher
    redirect_to @post.parent
  end

  def index
    @posts = Post.where("private = 'f' OR user_id = ?", current_user).order("created_at DESC")
  end

  def show
    @post = Post.find(params[:id])

    # Do not show if this is a private post and this user is not the owner
    if (@post.private && (@post.user != current_user))
      redirect_to root_path
      return
    end

    if @post.ptype == LINK_TYPE || @post.ptype == TWEET_TYPE
      redirect_to @post.parent
    end

    @children = @post.children.order(:position)

    @new_post = Post.new

    @cutPost
    if (session[:cutPostValue] && session[:cutPostValue] > 0)
      @cutPost = Post.find(session[:cutPostValue])
      if (current_user != @cutPost.user)
        @cutPost = nil
        session[:cutPostValue] = 0
      end
    end
  end

  def new
    @post = Post.new
    @post.ptype = TWEET_TYPE
    @parent_id = params[:parent_id]
    @parent_post = Post.find(@parent_id)
    @parent_title = @parent_post.title

    # Do not show the new post page if not logged in or owner of parent
    if !current_user || current_user != @parent_post.user
      redirect_to @parent_post
    end
  end

  def create
    my_params = post_params()
    p "params (next line):"
    p params
    p "my_params (next line): "
    p my_params

    @post = Post.new(my_params)
    @post.user = current_user

    if my_params[:parent_id]

      @parent_post = Post.find(my_params[:parent_id])
      if current_user && @parent_post.user == current_user

        PostChecker(@post)

        if @post.save
          flash[:notice] = "New #{ @post.getTypeString } was created successfully."
          redirect_to @post
          return
        else
          render :show
          return
        end
      end
    end

    #There was something wrong with the create
    redirect_to root_path

  end

  def edit
    @post = Post.find(params[:id])
    @parent_post = @post.parent

    # Do not show the edit page if not logged in or not the post's user
    if (!current_user || (current_user != @post.user))
      redirect_to root_path
      return
    end
  end

  def update
    my_params = post_params()
    p "params (next line):"
    p params
    p "my_params (next line): "
    p my_params

    @post = Post.find(params[:id])

    # Don't update a post if not logged in as the post's owner
    if !current_user || current_user != @post.user
      redirect_to root_path
      return
    end 
    puts "Authenticated and authorized update. Will now attempt to save..."

    if @post.update_attributes(my_params)
      puts "Successfully updated."
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    puts "Attempting to delete"

    # user must be logged in to delete anything
    if current_user == @post.user
      puts "User is logged in and is the owner"
      parent_post = @post.parent

      # Must have a parent post, don't destroy a post if it doesn't have a parent.
      if parent_post
        if @post.destroy
          redirect_to parent_post
          return
        end
      end
    end

    render :show
  end

  def post_params
    params.require(:post).permit(:parent_id, :title, :body, :ptype, :private)
  end

  private

  def url_checker(inputString)
    resultingString = inputString
    if !inputString.starts_with?("http://")
      resultingString = "http://" + resultingString
    end
    resultingString
  end

  def PostChecker(p)
    if p.ptype == LINK_TYPE
      p.body = url_checker p.body
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  def IsVisible?(p)
    p.private == false || p.user == current_user
  end

  def PrivacyIcon(p)
    if !p.private
      "glyphicon glyphicon-globe"
    else
      "glyphicon glyphicon-lock"
    end
  end

  def GetPrivacyString(p)
    p.private ? "private" : "public"
  end

  def MovePostButton(p)
    str = "<span data-toggle='tooltip' data-placement='top' title='move this to a different Folder'>" + link_to('move', post_move_folder_path(p), class: 'btn btn-default btn-xs') + "</span>"
    str.html_safe
  end

end

app/views/posts/_breadcrumbs.html.erb
<% 
  # _breadcrumbs.html.erb
  # Displays a list of breadcrumbs to the current folder.
  # input: post
%>
<ol class="breadcrumb">
  <li></li>
  <% post.ancestors.each do |p| %>
    <li><%= link_to(p.title, p) %></li>
  <% end %>
  <li class="active"><%= post.title %></li>
  <% if post.ptype == FOLDER_TYPE %>
    <li></li>
  <% end %>
</ol>

app/views/posts/_folder_form.html.erb
<%= form_for post do |f| %>
  <%= f.hidden_field :parent_id, value: parent_id %>
  <%= f.hidden_field :ptype, value: FOLDER_TYPE %>

  <%= f.label "Folder Name:" %>
  <%= f.text_field :title, :autofocus=>true, class: 'form-control' %>

  <%= f.label "Folder Subtitle:"%>
  <%= f.text_field :body, placeholder: "(Not required)", class: 'form-control' %>

  <%= f.radio_button :private, true, checked: true %>
  <%= f.label "Private" %>
  <%= f.radio_button :private, false %>
  <%= f.label "Public" %>

  <br/>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/posts/_folder_show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>
      <span class="<%= PrivacyIcon(post) %> iconPadding" data-toggle="tooltip" title="<%= GetPrivacyString(post) %>" data-placement="top"></span>
      <span class="<%= post.icon %> iconPadding" data-toggle="tooltip" title="<%= post.getTypeString %>" data-placement="top"></span>
      <%= post.title %>
    </h1>

    <% if current_user && current_user == post.user %>
      <% if post.ptype == FOLDER_TYPE %>
        <button class="btn btn-info btn-xs pull-right" data-toggle="modal" data-target="#editFolderModal">edit</button>  
        <div class="modal fade" id="editFolderModal" tabindex="-1" role="dialog" aria-labelledby="editFolderModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="editModalLabel">Edit Folder</h4>
              </div>
              <div class="modal-body">
                <%= render partial: "folder_form", locals: {post: post, parent_id: post.parent_id }%>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <%= link_to 'edit', edit_post_path(post), class: 'btn btn-info btn-xs pull-right' %>
      <% end %>
    <% end %>
   
    <% case post.ptype %>
    <% when BLOG_TYPE %>
      </div>
      <div class="panel-body">
        <div class="">
          <%= markdown post.body %>
        </div>
      </div>
    <% when FOLDER_TYPE %>
        <h3 class="small"> <%= post.body %></h3>
      </div>
      <div class="panel-body">
        <% children.each do |childpost| %>
          <% if IsVisible?(childpost) %>
            <%= render childpost %>
          <% end %>
        <% end %>
        <% if children.count == 0 %>
          <div class="panel"><i>This folder is empty.</i></div>
        <% end %>

        <p><%= link_to "+ New Note", new_post_path(:parent_id => post.id), class: 'btn btn-success' if (current_user && post.user == current_user) %></p>

        <% if current_user && post.user == current_user %>
          <button class="btn btn-primary" data-toggle="modal" data-target="#newFolderModal">+ New Folder</button>
          <div class="modal fade" id="newFolderModal" tabindex="-1" role="dialog" aria-labelledby="newFolderModalLabel" aria-hidden="true" >
            <div class="modal-dialog modal-sm">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title" id="myModalLabel">Create a New Folder</h4>
                </div>
                <div class="modal-body">
                  <%= render partial: "folder_form", locals: {post: new_post, parent_id: post.id} %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
</div>
<p><%= link_to "Back", post.parent, class: 'btn btn-default pull-left' if post.parent %></p>

<% if current_user && current_user == post.user && current_user.root != post %>
  <small>
    <%= link_to "Delete this #{post.ptype}", post, method: :delete, data: {confirm: "Are you sure you want to delete \"#{post.title}\""}, class: 'btn btn-danger pull-right' %>
  </small>
<% end %>

app/views/posts/_post.html.erb
<!-- views/posts/_post.html.erb /-->
<div class="media panel">
  <div class="<%= 'bg-warning' if session[:cutPostValue] == post.id %>">
    <% if current_user && post.user == current_user %>
      <div class="pull-left">
        <div data-toggle="tooltip" data-placement="top" title="move up"><%= link_to image_tag("uparrow.png", width: 21, height: 15, style: "opacity: 0.3;"), post_move_up_path(post), class: "btn btn-xs" %></div>
        <div data-toggle="tooltip" data-placement="bottom" title="move down"><%= link_to image_tag("downarrow.png", width: 21, height: 15, style: "opacity: 0.3;"), post_move_down_path(post), class: "btn btn-xs" %></div>
      </div>
    <% end %>

    <h4 style="vertical-align: middle;">
      <span data-toggle="tooltip" data-placement="top" title="<%= GetPrivacyString(post) %>" class="pull-left iconPadding <%= PrivacyIcon(post) %>"></span>
      <span data-toggle="tooltip" data-placement="top" title= "<%= post.getTypeString %>"class="<%= post.icon %> pull-left iconPadding"></span>
    </h4>

    <div class="media-body" style="padding-left: 1em;">
      <% case post.ptype %>
      <% when FOLDER_TYPE %>
        <h4 class="media-heading">
          <%= link_to (" " + post.title), post %>
        </h4>
        <%= post.body %>
        <div class="pull-right">
          <small><i><%= time_ago_in_words(post.updated_at) %> ago</i></small>
          <% if current_user && current_user == post.user %>
            <%= MovePostButton(post) %>
          <% end %>
        </div>
      <% when LINK_TYPE %>
        <h4 class="media-heading"><%= post.title %></h4>
        <%= link_to(" " + post.body, post.body, class: 'pull-left') %>
        <div class='pull-right'>
          <small><i><%= time_ago_in_words(post.updated_at) %> ago</i></small>
          <% if current_user && current_user == post.user %>
            <%= link_to 'edit', edit_post_path(post), class: 'btn btn-default btn-sm' %>
            <%= MovePostButton(post) %>
            <%= link_to 'delete', post, method: :delete, data: {confirm: 'Are you sure you want to delete this link?'}, class: 'btn btn-danger btn-xs glyphicon glyphicon-remove danger' %>
          <% end %>
        </div>
      <% when BLOG_TYPE %>
        <h4 class="media-heading">
          <%= link_to " " + post.title, post %>
        </h4>
        <div class="pull-right">
          <small><i><%= time_ago_in_words(post.updated_at) %> ago</i></small>
          <% if current_user && current_user == post.user %>
            <%= MovePostButton(post) %>
          <% end %>
        </div>
      <% when TWEET_TYPE %>
        <h4 class="media-heading">
          <%= post.title %>
        </h4>
        <%= markdown post.body %>
        <div class='pull-right'>
          <small><i><%= time_ago_in_words(post.updated_at) %> ago</i></small>
          <% if current_user && current_user == post.user %>
            <%= link_to 'edit', edit_post_path(post), class: 'btn btn-default btn-sm' %>
            <%= MovePostButton(post) %>
            <%= link_to 'delete', post, method: :delete, data: {confirm: "Are you sure you want to delete this note?"},class: 'btn btn-danger btn-xs glyphicon glyphicon-remove danger' %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_post_form.html.erb
<ul class="nav nav-tabs">
  <li class="<%='active' if post.ptype == TWEET_TYPE %>"><a href="#tweet" data-toggle="tab">Add a Note</a></li>
  <li class="<%='active' if post.ptype == LINK_TYPE %>"><a href="#link" data-toggle="tab">Post a Link</a></li>
  <li class="<%='active' if post.ptype == BLOG_TYPE %>"><a href="#blog" data-toggle="tab">Write a new Blog Post</a></li>
  <!--<li><a href="#folder" data-toggle="tab">Create a new Folder</a></li>/-->
</ul>
<div class="tab-content">
  <div class="tab-pane <%='active' if post.ptype == TWEET_TYPE %>" id="tweet">
    <%= form_for post do |f| %>
      <%= f.hidden_field :parent_id, value: parent_id %>
      <%= f.hidden_field :ptype, value: TWEET_TYPE %>

      <%= f.label "Note title:", class: 'form-label' %>
      <%= f.text_field :title, :autofocus=>true, class: 'form-control' %>

      <%= f.label "Note message:", class: 'form-label' %>
      <%= f.text_area :body, placeholder: "(Not required)", class: 'form-control' %>

      <%= f.radio_button :private, true, checked: true %>
      <%= f.label "Private" %>
      <%= f.radio_button :private, false %>
      <%= f.label "Public" %>
      <br/>
      <%= f.submit "Save", class: 'btn btn-success'%>
    <% end %>
  </div>
  <div class="tab-pane <%='active' if post.ptype == LINK_TYPE %>" id="link">
    <%= form_for post do |f| %>
      <%= f.hidden_field :parent_id, value: parent_id %>
      <%= f.hidden_field :ptype, value: LINK_TYPE %>

      <%= f.label "Title for Link" %>
      <%= f.text_field :title, :autofocus=>true, class: 'form-control' %>

      <%= f.label "URL:"%>
      <%= f.text_field :body, placeholder: "http://", class: 'form-control' %>

      <%= f.radio_button :private, true, checked: true %>
      <%= f.label "Private" %>
      <%= f.radio_button :private, false %>
      <%= f.label "Public" %>
      <br/>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
  <div class="tab-pane <%='active' if post.ptype == BLOG_TYPE %>" id="blog">
    <%= form_for post do |f| %>
      <%= f.hidden_field :parent_id, value: parent_id %>
      <%= f.hidden_field :ptype, value: BLOG_TYPE %>

      <%= f.label "Blog Title:" %>
      <%= f.text_field :title, :autofocus=>true, class: 'form-control' %>

      <%= f.label "Blog Content:"%>
      <%= f.text_area :body, rows: 15, placeholder: "Type your text here.", class: 'form-control' %>

      <%= f.radio_button :private, true, checked: true %>
      <%= f.label "Private" %>
      <%= f.radio_button :private, false %>
      <%= f.label "Public" %>

      <br/>
      <div class="">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Click here to show instructions on how to format your blog post
        </a>
      </div>
      <br/>
      <div id="collapseOne" class="collapse ">
        <ul>
          <li>To list bullet points like this, start each line with an asterisk (*)</li>
          <li>Surround *your text* with asterisks (*) to <i>make it italic</i></li>
          <li>Surround **your text** with double asterisks (**) to <b>make it bold</b></li>
          <li>To include a link use brackets and parentheses: [link text](www.linkURL.com)</li>
          <li>Surround ~~your text~~ with double tildes to add <del>strikethrough</del> </li>
        </ul>
        <br/>
      </div>

      <%= f.submit "Save", class: 'btn btn-success' %>  
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1><span class="glyphicon glyphicon-pencil iconPadding"></span>   <small>Edit:</small> <%= @post.title %></h1>
  </div>
  <div class="panel-body">
    <%= render partial: 'post_form', locals: {post: @post, parent_id: @post.parent_id} %>
  </div>
</div>

<%= button_to @post, class: 'btn btn-default', method: :get do %>
  <span class="glyphicon glyphicon-arrow-left"></span> Back (without saving)
<% end %>

<br/><br/><br/><br/><br/>
<hr/>

<%= render partial: 'breadcrumbs', locals: {post: @parent_post} %>
<%= render partial: 'folder_show', locals: {post: @parent_post, children: @parent_post.children.order(:position), new_post: @post} %>

app/views/posts/index.html.erb
<h1>Newsfeed</h1>

<div class="panel media" >
  <div class="panel-body">
  <%= render partial: @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1><span class="glyphicon glyphicon-plus iconPadding"></span>   <small>Add a new note in folder:</small> <%= @parent_title %></h1>
  </div>
  <div class="panel-body">
    <%= render partial: 'post_form', locals: {post: @post, parent_id: @parent_id} %>
  </div>
</div>

<a class="btn btn-default" href="<%= post_path(@parent_id)%>">
  <span class="glyphicon glyphicon-arrow-left"></span> Back (without saving)
</a>

<br/><br/><br/><br/><br/>
<hr/>
<%= render partial: 'breadcrumbs', locals: {post: @parent_post} %>
<%= render partial: 'folder_show', locals: {post: @parent_post, children: @parent_post.children.order(:position), new_post: @post} %>

app/views/posts/show.html.erb
<!-- views/posts/show.html.erb /-->
<%= render partial: 'breadcrumbs', locals: {post: @post} %>

<% if session[:cutPostValue] && session[:cutPostValue] > 0 %>
  <div class="alert alert-warning">
  <p><%= link_to ("Click here to move your '"+@cutPost.title+"' "+@cutPost.getTypeString), post_paste_into_folder_path(@post) %> into your '<%= @post.title %>' folder. <%= link_to "(Cancel move)", post_paste_cancel_path(@post) %>.</p>
  </div>
<% end %>

<%= render partial: 'folder_show', locals: {post: @post, children: @children, new_post: @new_post} %>