config/routes.rb
Kevlinks::Application.routes.draw do

  devise_for :users
  get "welcome/index"
  get "welcome/about"
  get "welcome/example"

  root to: 'welcome#index'
  
  resources :posts do
    get '/move_up', to: 'posts#move_up'
    get '/move_down', to: 'posts#move_down'
    get '/move_folder', to: 'posts#move_folder'
    get '/paste_into_folder', to: 'posts#paste_into_folder'
    get '/paste_cancel', to: 'posts#paste_cancel'
  end
  resources :users, only: [:index, :show]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FolderNotes</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'FolderFavicon.png' %>
  </head>
  <body>

    <!-- Static navbar -->
    <div class="navbar navbar-default navbar-inverse navbar-static-top" role="navigation">
      <div class="container">

        <ul class="nav navbar-nav navbar-header">
          <li>
            <a class= "navbar-link" href="<%= root_path %>">
              <% if current_user %>
                <span class="glyphicon glyphicon-home"></span>
              <% end %>
              FolderNotes.com — Beta Version
            </a>
          </li>
        </ul>

        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

            <li><p class="navbar-text">|</p></li>
            <!--<li><%= link_to "Newsfeed", posts_path, id: 'newsfeed_link' %></li><li><p class="navbar-text">|</p></li>/-->
            <li><%= link_to "About", welcome_about_path %></li><li><p class="navbar-text">|</p></li>
            <!--<li><%= link_to "Other Users", users_path %></li>/-->
            <li><%= link_to "Example", welcome_example_path %></li><li><p class="navbar-text">|</p></li>

          </ul>
          <ul class="nav navbar-nav navbar-right">

            <% if current_user %>
              <li class="active">
                <a href="<%= root_path %>">
                  <span class="glyphicon glyphicon-home"></span>
                  Hello, <%= current_user.email %> !
                </a>
              </li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'navbar-link' %></li>
            <% else %>
              <li><p class="navbar-text">|</p></li>
              <li class=""><%= link_to "Sign In", new_user_session_path %></li>
              <li><p class="navbar-text">|</p></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
    <!-- flash is a rails object that gets cleared after the next action /-->
    <% if (flash[:notice] && !(flash[:notice].blank?)) %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>


      <%= yield %>
    </div>

    <hr/>

  </body>
</html>